name: Patch, build and release Wine for Rhino upon tagging the repository *rhino*

on:
  push:
    #branches: [ "main" ] # trigger the action on each commit
    tags:
      - '*rhino*' # trigger the action when tagged with *rhino* 
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout source, submodules
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install dependencies
        run: |
          #sudo dpkg --add-architecture i386 # not necessary?
          sudo apt-get update
          # Install build dependencies
          sudo apt-get install -y \
            build-essential git autoconf bison flex \
            python3 pkg-config \
            gcc-mingw-w64 \
            libx11-dev libxext-dev libxrandr-dev \
            libxcomposite-dev libxcursor-dev \
            libxi-dev libxinerama-dev libxrender-dev libxxf86vm-dev \
            libxfixes-dev libxdamage-dev \
            libfreetype-dev libfontconfig-dev \
            libgnutls28-dev \
            libgl-dev \
            libvulkan-dev \
            libwayland-dev libxkbregistry-dev \
            libpulse-dev \
            libcups2-dev libpcap-dev libsdl2-dev libv4l-dev \
            ocl-icd-opencl-dev libpcsclite-dev unixodbc-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libssl-dev
      - name: Apply the patch by ItHasLegs
        run: |
          cd wine-src
          git apply ../patch/rhino8-wine.patch
      - name: Compile
        run: |
          mkdir wine-build
          cd wine-build
          ../wine-src/configure --enable-archs=i386,x86_64 \
            --with-wayland --with-vulkan --with-x
          make -j$(nproc)
          make install DESTDIR="$GITHUB_WORKSPACE/wine-runner-stage"
      - name: Name and package
        run: |
          TAG="${{ github.ref_name }}"
          #RELEASE_NAME="${TAG}_$(date +'%y%m%d')"
          RELEASE_NAME="${TAG}"
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          tar -cf "${RELEASE_NAME}.tar.xz" -I 'xz -9e' -C wine-runner-stage/usr/local .
      - name: Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ env.RELEASE_NAME }}
          body: "Release of Wine patched to run Rhino, version ${{ github.ref_name }}"
          generate_release_notes: true
          files: ${{ env.RELEASE_NAME }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}